### ISSUE TITLE
Not working as expected or ?

### ISSUE THREAD

**Issue by vingerha** [OzGav/opensky#1]
Hi, I reworked it a bit to be able to install it as opensky2 via hacs, with the same name as the core integration it would not start, not sure how you got this to work
It does load but then I receive this...
```
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'opensky-network.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```
My config
```
  - platform: opensky2
    name: Nice Airport2
    radius: 40
    latitude: 43.6595
    longitude: 7.2127
    username: user
    password: pwd
    altitude: 9000

**Comment by vingerha** [comment]
On my ideas. I am trying to get a notification with details on flights entering a certain airport.
I would like to have data on the flight but with the icao that opensky is using for the 1st detection, you need a second call to SO  to get flightdetails. As this is all free I am of course OK...flightaware has massive data but this comes at a price too.
1. use opensky core or this one to get the icao
2. use a command line curl to get the details
3. depending on iata details, send the notification
I am aiming to use a input helper to provide the iata and this allows me to get notified when the flight in focus
To be tested is if I can use one for exit and another for entry with different hight and/or range

**Comment by OzGav** [comment]
Yeah I saw those errors when I upgraded but I haven’t had time to look at it yet. There is work going on with the official integration to get that up to speed so keep an eye out for that as well. 

I have this automation at the moment that is currently hard coded but I was thinking of trying to use an input helper to identify a specific flight 

```
- alias: "Flight entry notification"
  trigger:
    platform: event
    event_type: opensky_entry
  condition:
    condition: template
    value_template: "{{ 'ABC' in trigger.event.data.callsign }}"
  action:
    service: notify.mobile_app_gavin_pixel_4a
    data:
      message: "Flight entry of {{ trigger.event.data.callsign }}"
      
```
